# Root Logger
rootLogger.level = info
rootLogger.appenderRefs = console, file
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.file.ref = FileAppender

# Console Appender
appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.disableAnsi = false
appender.console.layout.noConsoleNoAnsi = false
appender.console.layout.pattern = [%d{HH:mm:ss}] [%t] %msg%n

# File Appender
appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = logs/test.log
appender.file.append = false
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%d{yyyy-MM-dd HH:mm:ss}] [%t] %-5level %c - %replace{%msg}{\u001B\\[[;\\d]*m}{}%n
